### ISSUE TITLE
Implement the empty base class optimisation on the copier member

### ISSUE THREAD

**Issue by Twon** [jbcoe/indirect#20]
Current indirect has the issues:
```cpp
sizeof(indirect<int>) != sizeof(std::unique_ptr<int>)
```
This because the copier member, although by default implemented as an empty structure with a call operator member function with no data member, the compiler by default has to ensure that and addressable memory location exist to reference if the address of this member was taken.

In C++ 20 we can fix this with the  [[no_unique_address] attribute](https://en.cppreference.com/w/cpp/language/attributes/no_unique_address).  However, to support this in C++17 we will have to use the empty base class optimisation, in the same way, that std::unique_ptr implementations do to remove the size of the deleted: https://stackoverflow.com/questions/33289652/c-stdunique-ptr-why-isnt-there-any-size-fees-with-lambdas

**Comment by jbcoe** [comment]
Nice summary. Are you happy to tackle this?

**Comment by Twon** [comment]
Yes, indeed I am.  I submitted a PR addressing this, and it's now merged to master after being reviewed.
